apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
  labels:
    app: flask-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-todo
          image: quay.io/ytooyama/flask-todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
